### ISSUE TITLE
array_indexof for missing element

### ISSUE THREAD

**Issue by aclemons** [makefu/array#7]
A script running with set -e will stop if you test an element not in the array with array_indexof. This should just return the value -1 to make it simple to test existence.

**Comment by aclemons** [comment]
I wasn't sure how to best handle this before, but with 4z3's latest changes, I can also handle this in a similar way.

**Comment by 4z3** [comment]
Isn't a non-zero exit code the desired behavior as it allows you to write something like
```
if ! index=$(echo "$array" | array_indexof "$element"); then
  # do something to handle the error
fi
```
instead of
```
if index=$(echo "$array" | array_indexof "$element") && test "$index" -ge 0; then
  # do something to handle the error
fi
```
?

**Comment by aclemons** [comment]
I just grepped all my scripts where I am using array and yes, you are right. The initial behaviour is actually better in most of my cases since.

**Comment by aclemons** [comment]
Ok, I updated the pull request to still return non-zero when not matching but left it with awk.

**Comment by 4z3** [comment]
LGTM
