### ISSUE TITLE
array no longer works on freebsd/openbsd

### ISSUE THREAD

**Issue by aclemons** [makefu/array#9]
The sed expressions only work with gnu sed.

These work on both freebsd/openbsd (and continue to work on linux)

```shell
array_element_encode() {
  sed 's/%/%25/g' | sed -e :a -e '$!N; s/\n/%0A/; ta'
}

array_element_decode() {
  sed -e 's/%0[aA]/\
/g' -e 's/%25/%/g'
}
```
I am not really sure if that case-sensitivity in _decode is needed?

**Comment by 4z3** [comment]
Omitting `:a`, `$!N`, and `ta` will break with multi-line elements.

**Comment by 4z3** [comment]
nvm, I didn't read it properly

**Comment by 4z3** [comment]
Care to make it a PR?

**Comment by aclemons** [comment]
Ok, added.
